version: 2
updates:
- package-ecosystem: nuget
  directory: "/eFormAPI/Plugins/WorkOrders.Pn"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microting.eForm
    versions:
    - 4.3.14
    - 4.3.17
    - 4.3.18
    - 4.3.9
    - 4.4.14
    - 4.4.22
    - 4.4.31
    - 4.4.36
    - 4.4.6
    - 4.4.7
    - 4.4.9
    - 4.5.2
  - dependency-name: Microting.eFormApi.BasePn
    versions:
    - 2.0.101
    - 2.0.102
    - 2.0.103
    - 2.0.104
    - 2.0.108
    - 2.0.112
    - 2.0.122
    - 2.0.127
    - 2.0.88
    - 2.1.2
  - dependency-name: Microting.WorkOrderBase
    versions:
    - 1.2.11
    - 1.2.25
    - 1.2.27
    - 1.2.32
    - 1.2.33
    - 1.2.40
    - 1.2.44
  - dependency-name: Rebus
    versions:
    - 6.4.1
    - 6.5.0
    - 6.5.2
    - 6.5.3
    - 6.5.4
